site:
  title: Dialog
  start_page: dialog::index.adoc
content:
  sources:
  - url: https://github.com/Dialog-IF/dialog.git
    branches: ~
    tags: release-*
    start_path: manual
  - url: https://github.com/Dialog-IF/dialog.git
    branches: main
    start_path: manual
    # This is all set up, just waiting for aamachine/antora/ROOT/nav.adoc to be created
  - url: https://github.com/Dialog-IF/aamachine.git
    branches: main
    start_path: antora
  - url: https://github.com/hlship/dialog-ide.git
    branches: main      
    start_path: docs    
  - url: https://github.com/hlship/dialog-ide.git
    branches: ~
    tags: v*      
    start_path: docs        
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-overrides 
asciidoc: 
  extensions:
    - lib/macros.js
antora:
  extensions:
    - '@antora/lunr-extension'
